apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs-helloworld-{{.Release.Name}}   #this will be populated at run time like *helm install my-release ./my-chart* my release will be replaced with .Release.Name value in yaml file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acs-helloworld-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: acs-helloworld-{{.Release.Name}}
    spec:
      containers:
      - name: acs-helloworld-{{.Release.Name}}
        image: neilpeterson/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} #it will reference values.yaml for its value we can set this at run time as well helm install my-release ./my-chart -f values.yaml
spec:
  type: {{ .Values.serviceType }}   #it will reference values.yaml for its value we can set this at run time as well. helm install my-release ./my-chart --set serviceType=NodePort
  ports:
  - port: 80
  selector:
    app: acs-helloworld-{{.Release.Name}}
